import type { Lead, Buyer } from './types';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);

export const DEMO_LEADS: Lead[] = [
  {
    id: 'demo-1',
    title: '412 W 3rd St, Chester, PA 19013',
    category: 'Pre-Foreclosure',
    categoryId: 'fc',
    location: 'Chester City, PA 19013',
    zip: '19013',
    details: 'Lis pendens filed Jan 2026. Mortgage default — behind on payments 6 months. Single family, 3bd/1ba, 1,100 sqft. Built 1952. Owner since 2008.',
    sourceUrl: 'https://delaware.pa.publicsearch.us/',
    source: 'scrub',
    stage: 'contacted',
    followUp: daysAgo(-2),
    stackedCategories: ['fc', 'tx'],
    stackedLabels: ['Pre-Foreclosure', 'Tax Delinquent'],
    stackCount: 2,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: {
      owner: 'James Wilson',
      phones: ['(484) 555-0142', '(610) 555-0398'],
      emails: ['james.wilson@gmail.com'],
      mailingAddress: '412 W 3rd St, Chester, PA 19013',
      relatives: 'Patricia Wilson, Michael Wilson',
      notes: 'Owner-occupied. Owner since 2008.',
      timestamp: daysAgo(3),
    },
    comps: {
      estimatedArv: 95000,
      confidence: 'high',
      comparables: [
        { address: '430 W 3rd St, Chester, PA', soldPrice: '$92,000', saleDate: '11/15/2025', bedBath: '3bd/1ba', sqft: '1,050' },
        { address: '505 Morton Ave, Chester, PA', soldPrice: '$98,000', saleDate: '01/08/2026', bedBath: '3bd/1ba', sqft: '1,150' },
        { address: '618 Kerlin St, Chester, PA', soldPrice: '$88,000', saleDate: '12/02/2025', bedBath: '2bd/1ba', sqft: '980' },
      ],
      timestamp: daysAgo(3),
    },
    offer: { arv: 95000, repairs: 15000, wholesaleFee: 8000, holdingCosts: 3000, maxOffer: 40500 },
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Pre-Foreclosure scrub', date: daysAgo(10) },
      { id: 2, type: 'skip_trace', text: 'Skip trace completed — owner James Wilson, 2 phones found', date: daysAgo(8) },
      { id: 3, type: 'comps', text: 'Comps pulled — ARV est. $95,000 (high confidence)', date: daysAgo(7) },
      { id: 4, type: 'stage', text: 'Stage changed: New → Contacted', date: daysAgo(5) },
      { id: 5, type: 'call', text: 'Called owner — interested but wants to think about it. Follow up Friday.', date: daysAgo(5) },
      { id: 6, type: 'offer', text: 'Max offer calculated: $40,500 (70% rule)', date: daysAgo(4) },
    ],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },
  {
    id: 'demo-2',
    title: '1025 Morton Ave, Chester, PA 19013',
    category: 'Tax Delinquent',
    categoryId: 'tx',
    location: 'Chester City, PA 19013',
    zip: '19013',
    details: 'Delinquent property taxes since 2023, $6,800 owed. Upset sale scheduled. Single family, vacant. Owner lives out of state.',
    sourceUrl: 'https://delcopa.gov/treasurer/backyeartaxes',
    source: 'scrub',
    stage: 'new',
    followUp: null,
    stackedCategories: ['tx', 'vc'],
    stackedLabels: ['Tax Delinquent', 'Vacant'],
    stackCount: 2,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: null,
    comps: null,
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Tax Delinquent scrub', date: daysAgo(5) },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'demo-3',
    title: '227 Pine St, Darby, PA 19023',
    category: 'Probate/Estate',
    categoryId: 'pb',
    location: 'Darby, PA 19023',
    zip: '19023',
    details: 'Inherited property, probate filed Sept 2025. Estate of Margaret Thompson. Heirs live in New Jersey, want to sell. 3bd/1.5ba, 1,300 sqft.',
    sourceUrl: '',
    source: 'scrub',
    stage: 'appt',
    followUp: daysAgo(-1),
    stackedCategories: ['pb'],
    stackedLabels: ['Probate/Estate'],
    stackCount: 1,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: {
      owner: 'Estate of Margaret Thompson',
      phones: ['(856) 555-0271'],
      emails: ['r.thompson.nj@yahoo.com'],
      mailingAddress: '45 Elm Dr, Cherry Hill, NJ 08003',
      relatives: 'Robert Thompson (son), Linda Davis (daughter)',
      notes: 'Absentee heirs in NJ. Property unoccupied since Aug 2025.',
      timestamp: daysAgo(8),
    },
    comps: {
      estimatedArv: 125000,
      confidence: 'medium',
      comparables: [
        { address: '310 Pine St, Darby, PA', soldPrice: '$118,000', saleDate: '10/20/2025', bedBath: '3bd/1ba', sqft: '1,200' },
        { address: '145 Chester Pike, Darby, PA', soldPrice: '$132,000', saleDate: '01/15/2026', bedBath: '3bd/2ba', sqft: '1,400' },
        { address: '401 Main St, Darby, PA', soldPrice: '$121,000', saleDate: '11/30/2025', bedBath: '3bd/1ba', sqft: '1,250' },
      ],
      timestamp: daysAgo(6),
    },
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Probate scrub', date: daysAgo(12) },
      { id: 2, type: 'skip_trace', text: 'Skip trace completed — heir Robert Thompson in NJ', date: daysAgo(8) },
      { id: 3, type: 'stage', text: 'Stage changed: New → Contacted', date: daysAgo(6) },
      { id: 4, type: 'comps', text: 'Comps pulled — ARV est. $125,000 (medium confidence)', date: daysAgo(6) },
      { id: 5, type: 'call', text: 'Spoke with Robert Thompson — scheduling walkthrough', date: daysAgo(4) },
      { id: 6, type: 'stage', text: 'Stage changed: Contacted → Appointment', date: daysAgo(3) },
      { id: 7, type: 'followup', text: 'Follow-up set for walkthrough appointment', date: daysAgo(3) },
    ],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
  {
    id: 'demo-4',
    title: '6820 Market St, Upper Darby, PA 19082',
    category: 'Code Violations',
    categoryId: 'cv',
    location: 'Upper Darby, PA 19082',
    zip: '19082',
    details: 'Multiple code violations — condemned, boarded windows, failed electrical inspection. Vacant 2+ years. Multi-family duplex.',
    sourceUrl: '',
    source: 'scrub',
    stage: 'new',
    followUp: null,
    stackedCategories: ['cv', 'vc'],
    stackedLabels: ['Code Violations', 'Vacant'],
    stackCount: 2,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: null,
    comps: null,
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Code Violations scrub', date: daysAgo(2) },
    ],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'demo-5',
    title: '740 Burmont Rd, Drexel Hill, PA 19026',
    category: 'Divorce',
    categoryId: 'dv',
    location: 'Drexel Hill, PA 19026',
    zip: '19026',
    details: 'Divorce filing — court-ordered property sale. Single family, 4bd/2ba, 1,800 sqft. Both parties motivated to sell quickly.',
    sourceUrl: '',
    source: 'scrub',
    stage: 'offer',
    followUp: daysAgo(-3),
    stackedCategories: ['dv'],
    stackedLabels: ['Divorce'],
    stackCount: 1,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: {
      owner: 'David & Susan Garcia',
      phones: ['(484) 555-0183', '(484) 555-0294'],
      emails: ['david.garcia@outlook.com'],
      mailingAddress: '740 Burmont Rd, Drexel Hill, PA 19026',
      relatives: 'Susan Garcia (co-owner)',
      notes: 'Both owners cooperative. Attorney involved.',
      timestamp: daysAgo(15),
    },
    comps: {
      estimatedArv: 215000,
      confidence: 'high',
      comparables: [
        { address: '810 Burmont Rd, Drexel Hill, PA', soldPrice: '$220,000', saleDate: '12/10/2025', bedBath: '4bd/2ba', sqft: '1,750' },
        { address: '215 Shadeland Ave, Drexel Hill, PA', soldPrice: '$208,000', saleDate: '02/01/2026', bedBath: '3bd/2ba', sqft: '1,650' },
        { address: '432 State Rd, Drexel Hill, PA', soldPrice: '$225,000', saleDate: '11/20/2025', bedBath: '4bd/2.5ba', sqft: '1,900' },
      ],
      timestamp: daysAgo(14),
    },
    offer: { arv: 215000, repairs: 10000, wholesaleFee: 10000, holdingCosts: 5000, maxOffer: 125500 },
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Divorce scrub', date: daysAgo(20) },
      { id: 2, type: 'skip_trace', text: 'Skip trace completed — both owners found', date: daysAgo(15) },
      { id: 3, type: 'comps', text: 'Comps pulled — ARV est. $215,000 (high confidence)', date: daysAgo(14) },
      { id: 4, type: 'stage', text: 'Stage changed: New → Contacted', date: daysAgo(12) },
      { id: 5, type: 'call', text: 'Called David — both want to sell, attorney reviewing', date: daysAgo(12) },
      { id: 6, type: 'stage', text: 'Stage changed: Contacted → Appointment', date: daysAgo(8) },
      { id: 7, type: 'note', text: 'Walkthrough completed. Minor cosmetic repairs needed.', date: daysAgo(6) },
      { id: 8, type: 'offer', text: 'Offer submitted: $125,500 (70% rule)', date: daysAgo(4) },
      { id: 9, type: 'stage', text: 'Stage changed: Appointment → Offer Made', date: daysAgo(4) },
    ],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(4),
  },
  {
    id: 'demo-6',
    title: '120 Lansdowne Ave, Lansdowne, PA 19050',
    category: 'Expired Listing',
    categoryId: 'ex',
    location: 'Lansdowne, PA 19050',
    zip: '19050',
    details: 'Expired MLS listing, 200 days on market, three price reductions. Originally listed at $165K, last price $139K. Single family 3bd/1ba.',
    sourceUrl: '',
    source: 'scrub',
    stage: 'contacted',
    followUp: daysAgo(1), // overdue!
    stackedCategories: ['ex'],
    stackedLabels: ['Expired Listing'],
    stackCount: 1,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: {
      owner: 'Linda Thompson',
      phones: ['(610) 555-0456'],
      emails: [],
      mailingAddress: '120 Lansdowne Ave, Lansdowne, PA 19050',
      relatives: 'Michael Thompson',
      notes: 'Owner-occupied, frustrated with market.',
      timestamp: daysAgo(5),
    },
    comps: null,
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Lead discovered via Expired Listing scrub', date: daysAgo(7) },
      { id: 2, type: 'skip_trace', text: 'Skip trace completed — owner Linda Thompson', date: daysAgo(5) },
      { id: 3, type: 'stage', text: 'Stage changed: New → Contacted', date: daysAgo(3) },
      { id: 4, type: 'call', text: 'Left voicemail. Will call back.', date: daysAgo(3) },
      { id: 5, type: 'followup', text: 'Follow-up call scheduled', date: daysAgo(3) },
    ],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(3),
  },
  {
    id: 'demo-7',
    title: '301 Long Ln, Upper Darby, PA 19082',
    category: 'FSBO',
    categoryId: 'fs',
    location: 'Upper Darby, PA 19082',
    zip: '19082',
    details: 'For sale by owner, 60 days on market, no showings. Single family 2bd/1ba, needs work. Owner relocating for job.',
    sourceUrl: '',
    source: 'manual',
    stage: 'new',
    followUp: null,
    stackedCategories: ['fs'],
    stackedLabels: ['FSBO'],
    stackCount: 1,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: null,
    comps: null,
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Spotted driving for dollars — FSBO sign in yard', date: daysAgo(1) },
    ],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'demo-8',
    title: '534 Oak Ln, Darby, PA 19023',
    category: 'Vacant',
    categoryId: 'vc',
    location: 'Darby, PA 19023',
    zip: '19023',
    details: 'Vacant and abandoned. Boarded up, overgrown yard. Neighbors say empty 3+ years. Possible tax lien.',
    sourceUrl: '',
    source: 'manual',
    stage: 'new',
    followUp: null,
    stackedCategories: ['vc', 'tx'],
    stackedLabels: ['Vacant', 'Tax Delinquent'],
    stackCount: 2,
    isDuplicate: false,
    stackedInto: null,
    skipTrace: null,
    comps: null,
    offer: null,
    activities: [
      { id: 1, type: 'note', text: 'Found driving for dollars — vacant, boarded, overgrown', date: daysAgo(0) },
    ],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
];

export const DEMO_BUYERS: Buyer[] = [
  {
    id: 'buyer-1',
    name: 'Keystone Capital LLC',
    type: 'flipper',
    priceRange: '$60K - $150K',
    properties: '12 purchases in past 12 months',
    contact: '(484) 555-0777',
    notes: 'Active flipper in Chester/Darby area. Cash buyer, closes in 14 days. Prefers single family.',
    createdAt: daysAgo(30),
  },
  {
    id: 'buyer-2',
    name: 'DelCo Properties LLC',
    type: 'landlord',
    priceRange: '$80K - $200K',
    properties: '8 purchases in past 12 months',
    contact: '(610) 555-0888',
    notes: 'Buy and hold investor. Targets Upper Darby and Drexel Hill. Looking for multi-family.',
    createdAt: daysAgo(45),
  },
  {
    id: 'buyer-3',
    name: 'Main Line Investments',
    type: 'developer',
    priceRange: '$100K - $300K',
    properties: '5 purchases in past 12 months',
    contact: '(610) 555-0999',
    notes: 'Developer doing gut rehabs. Handles larger projects. Cash or hard money.',
    createdAt: daysAgo(60),
  },
];
